### ISSUE TITLE
Scrolling lags.

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#74] opened 2019-07-21 18:37 UTC
Why scrolling is lagging? I am getting these outputs in console and scroll lags noticeably. Is this alright and nothing can be done?
 [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp; rolling forward by 0.066730
2019-07-21 21:35:28.575370+0300 testing[629:19916] [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp; rolling forward by 0.049998
2019-07-21 21:35:32.110095+0300 testing[629:19916] [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp; rolling forward by 0.299243
2019-07-21 21:35:33.497742+0300 testing[629:19916] [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp; rolling forward by 0.199321
2019-07-21 21:35:34.913068+0300 testing[629:19916] [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp;

**Comment by kizitonwose** [comment] 2019-07-27 12:19
Unfortunately, I cannot reproduce this.

**Comment by wellbranding** [comment] 2019-07-27 17:31
Ok, I will try to reproduce it and provide more details :) I thought it was common though

**Comment by kizitonwose** [comment] 2019-09-29 11:41
After some research, it seems these are just diagnostic messages dumped by classes which inherit from UIScrollView. If you still have proof that scrolling lags, do share. Will be closing this for now.

**Closed as completed by kizitonwose** 2019-09-29 11:41 UTC
