### ISSUE TITLE
Search bar issue

### ISSUE THREAD

**Issue by bkucharskiDev** [kizitonwose/CountryPickerView#47] opened 2019-03-21 20:07 UTC
Hey 👋 first of all thank you for this library! I'm using the latest version on iOS 12.1 and the problem with searchbar still occurs (I saw that it was already closed here https://github.com/kizitonwose/CountryPickerView/issues/13). Can you fix it? :)

<img width="381" alt="image" src="https://user-images.githubusercontent.com/31849847/54781707-4bbdc000-4c1d-11e9-8769-408c8c0099bb.png">

**Comment by bkucharskiDev** [comment] 2019-03-26 10:15
@kizitonwose?

**Comment by MhmdRizk** [comment] 2019-03-28 08:39
Hello I faced the same issue.

**Comment by kizitonwose** [comment] 2019-03-28 18:22
@bkucharskiDev @MhmdRizk 
I am not able to replicate this issue using the latest version of the library(2.2.4), can you confirm the version installed in your `Podfile.lock` file?

**Comment by bkucharskiDev** [comment] 2019-04-01 08:30
I am using Carthage as dependency manager. Version from Cartfile.resolved is "2.2.4"

**Comment by kizitonwose** [comment] 2019-04-04 10:11
I tested using CountryPickerView version `2.2.4` and Carthage today and still cannot reproduce the issue.
I would appreciate if someone creates a test project where this issue can be reproduced.
<img src="https://user-images.githubusercontent.com/15170090/55547631-9d5c5500-56c9-11e9-87c1-6c2bc47f404b.png" width="250">

**Comment by mauliksharma** [comment] 2019-04-19 12:01
I'm also facing this issue. `v2.2.4`, Xcode `v10.1`, Swift v4. @subhajitregor 
@kizitonwose I'll try and create a test project that reproduces the same.
@bkucharskiDev A temporary workaround would be to use the `datasource` function
`searchBarPosition(in countryPickerView:)` to return `.navigationBar`

**Comment by bkucharskiDev** [comment] 2019-04-29 10:28
@mauliksharma are you able to provide test project to reproduce this bug?

**Comment by applifypiyush** [comment] 2019-05-17 12:39
Hey, any update on this?
The steps as per my testing are, when you try to search something, say "ABC", and either using backspace or by tapping cross button, the search goes empty, with extra space on the top. 
version 2.2.4. 
Make sure the search position is set to .navigationBar.

**Comment by kizitonwose** [comment] 2019-07-14 12:15
Since I am not able to reproduce this issue on my end and no sample project has been provided to help reproduce the issue, I'll have to close this for now as it has been open for too long. 

Anyone with a sample project should leave a comment and I'll reopen the issue.

**Closed as completed by kizitonwose** 2019-07-14 12:15 UTC
