### ISSUE TITLE
How to change padding in UIView?

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#26] opened 2018-12-07 15:37 UTC
How can I change margin of country label and flag inside UIView which is used as CountryPickerView? Right now flag does not have any margin to the parent view..

**Comment by kizitonwose** [comment] 2018-12-08 12:44
`CountryPickerView` class has a `flagSpacingInView` property. I believe that's what you need.

**Comment by wellbranding** [comment] 2018-12-08 14:11
How does it work? which float should I provide? if I use CGFloat(bitPattern: 10) it does affect. If I use other float I get a crash. can you be more specific?
 Also how can I center text of country in the view?

**Comment by kizitonwose** [comment] 2018-12-08 22:39
It takes a regular CGFloat, e.g `1.0`, `2.5` etc
If you have an instance of `CountryPickerView` named `cpv`, you can change the value like this: `cpv.flagSpacingInView = 2.5`

Also, you cannot center the Country name on the list.

**Comment by wellbranding** [comment] 2018-12-09 16:47
It worked. However how can I move flag from the left edge itself?

**Comment by kizitonwose** [comment] 2018-12-09 21:13
You need to increase the `constant` value of the view's leading constraint.

**Comment by wellbranding** [comment] 2018-12-09 23:54
can you provide an example? :)

**Comment by kizitonwose** [comment] 2018-12-16 23:11
Using the same `cpv` from the example above, that would be: 
`cpv.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 20).isActive = true`
You can change the value of the `constant` parameter to fit your use case.

**Comment by kizitonwose** [comment] 2018-12-16 23:13
I'll be closing this issue now since the problem is solved.

**Closed as completed by kizitonwose** 2018-12-16 23:13 UTC
