### ISSUE TITLE
Cordova IOS support, bad podspec

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#68] opened 2019-06-11 05:03 UTC
The podspec is malformed, you cannot use it in other platforms like cordova. here is information:
https://stackoverflow.com/questions/50124893/this-target-might-include-its-own-product-for-nib-in-dependency
https://github.com/CocoaPods/CocoaPods/issues/7704
How soon can I expect a fix?

**Comment by kizitonwose** [comment] 2019-07-14 11:14
Unfortunately, I don't work with Cordova so I really can't help with this issue. You seem experienced with the Cordova platform, kindly help out if possible. 

Meanwhile, I'll be closing this issue as the podspec works in Xcode projects as intended. Feel free to reopen if you still need help.

**Closed as completed by kizitonwose** 2019-07-14 11:14 UTC
